from .cashflow_reader import StaticCashflowReader as StaticCashflowReader
from .cost_reader import StaticCostReader as StaticCostReader
from .customer_value_reader import StaticCustomerValueReader as StaticCustomerValueReader
from .revenue_reader import StaticRevenueReader as StaticRevenueReader
from .spend_reader import StaticSpendReader as StaticSpendReader
