"""Repository protocols for knowledge domain."""
from __future__ import annotations

from typing import Protocol, Sequence

from ..types import (
    Lesson,
    LessonQuery,
    MemoryLink,
    Pattern,
)

__all__ = [
    "LessonRepository",
    "PatternRepository",
    "MemoryLinkRepository",
]


class LessonRepository(Protocol):
    def save(self, lesson: Lesson) -> Lesson: ...
    def get(self, lesson_id: str) -> Lesson | None: ...
    def list_all(self) -> Sequence[Lesson]: ...
    def find(self, query: LessonQuery) -> Sequence[Lesson]: ...


class PatternRepository(Protocol):
    def save(self, pattern: Pattern) -> Pattern: ...
    def get(self, pattern_id: str) -> Pattern | None: ...
    def list_all(self) -> Sequence[Pattern]: ...
    def find_by_subject(self, subject: str) -> Sequence[Pattern]: ...


class MemoryLinkRepository(Protocol):
    def save(self, link: MemoryLink) -> MemoryLink: ...
    def list_for_target(self, target_id: str) -> Sequence[MemoryLink]: ...
    def list_for_source(self, source_id: str) -> Sequence[MemoryLink]: ...
    def list_all(self) -> Sequence[MemoryLink]: ...
