from __future__ import annotations

CANON_ORGANIZATION_FACT_VOCABULARY = True
ORGANIZATION_CREATED = "organization.created"
ORGANIZATION_UPDATED = "organization.updated"
ORGANIZATION_ARCHIVED = "organization.archived"
ORGANIZATION_FACT_TYPES = frozenset({ORGANIZATION_CREATED, ORGANIZATION_UPDATED, ORGANIZATION_ARCHIVED})

__all__ = [
    "CANON_ORGANIZATION_FACT_VOCABULARY",
    "ORGANIZATION_ARCHIVED",
    "ORGANIZATION_CREATED",
    "ORGANIZATION_FACT_TYPES",
    "ORGANIZATION_UPDATED",
]
