from __future__ import annotations

"""Canonical runtime action-name package surface."""

from core.actions import build_schema_registry
from core.actions.names import (
    ACTION_ADS_APPLY_EXECUTE_V1,
    ACTION_ADS_AUTOPILOT_TICK_V1,
    ACTION_AI_CEO_PLAN_V1,
    ACTION_APPLY_OFFER_PATCH_V1,
    ACTION_ENQUEUE_EVOLUTION_JOB_V1,
    ACTION_EXECUTE_PLAN_V1,
    ACTION_GROWTH_PROPOSAL_APPLY_V1,
    ACTION_GROWTH_PROPOSE_V1,
    ACTION_PRICING_SELECT_V1,
    ACTION_REWARD_OBSERVE_V1,
    ACTION_SUGGEST_OFFER_PATCH_V1,
)

CANON_RUNTIME_ACTION_NAMES_PUBLIC_API = True

__all__ = [
    'CANON_RUNTIME_ACTIONS_NAMESPACE',
    'CANON_RUNTIME_ACTION_NAMES_PUBLIC_API',
    'ACTION_ADS_APPLY_EXECUTE_V1',
    'ACTION_ADS_AUTOPILOT_TICK_V1',
    'ACTION_AI_CEO_PLAN_V1',
    'ACTION_APPLY_OFFER_PATCH_V1',
    'ACTION_ENQUEUE_EVOLUTION_JOB_V1',
    'ACTION_EXECUTE_PLAN_V1',
    'ACTION_GROWTH_PROPOSAL_APPLY_V1',
    'ACTION_GROWTH_PROPOSE_V1',
    'ACTION_PRICING_SELECT_V1',
    'ACTION_REWARD_OBSERVE_V1',
    'ACTION_SUGGEST_OFFER_PATCH_V1',
    'build_schema_registry',
]

CANON_RUNTIME_ACTIONS_NAMESPACE = True



