target-version = "py311"
line-length = 120

[lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM", "T20"]
ignore = ["E501", "E741", "B904", "SIM108"]

[lint.per-file-ignores]
"tests/*" = ["B", "SIM", "T20"]
"scripts/*" = ["T20"]

[format]
quote-style = "double"
indent-style = "space"
