EMPLOYEE_CREATED = "employee.created"
EMPLOYEE_ARCHIVED = "employee.archived"
EMPLOYEE_FACT_TYPES = frozenset({EMPLOYEE_CREATED, EMPLOYEE_ARCHIVED})

__all__ = ["EMPLOYEE_ARCHIVED", "EMPLOYEE_CREATED", "EMPLOYEE_FACT_TYPES"]
