from __future__ import annotations

from application.memory.business_memory_policy import BusinessMemoryPolicy, CANON_BUSINESS_MEMORY_POLICY

CANON_BUSINESS_MEMORY_POLICY_COMPAT_SHIM = True
CANON_BUSINESS_MEMORY_POLICY_FINAL_OWNER = "application.memory.business_memory_policy"
