from __future__ import annotations

from execution.business_operating_memory import project_business_memory_governance_summary
from application.memory.business_memory_governance import *

CANON_BUSINESS_MEMORY_GOVERNANCE_COMPAT_SHIM = True
CANON_BUSINESS_MEMORY_GOVERNANCE_FINAL_OWNER = "application.memory.business_memory_governance"
