from __future__ import annotations

from application.planning.long_horizon_planner import CANON_LONG_HORIZON_PLANNER, LongHorizonPlanView, LongHorizonPlanner

CANON_LONG_HORIZON_PLANNER_COMPAT_SHIM = True
CANON_LONG_HORIZON_PLANNER_FINAL_OWNER = "application.planning.long_horizon_planner"
CANON_LONG_HORIZON_PLANNER_SURFACE = "LongHorizonPlanner"
