"""Thin compatibility shim for the canonical runtime observability owner."""

from __future__ import annotations

from runtime.runtime_observability import (
    CANON_RUNTIME_OBSERVABILITY_AUDIT_ONLY,
    CANON_RUNTIME_OBSERVABILITY_NO_DECISION_LOGIC,
    CANON_RUNTIME_OBSERVABILITY_ONE_TRACE_STORY,
    CANON_RUNTIME_OBSERVABILITY_OWNER,
    RuntimeObservability,
)

CANON_RUNTIME_OBSERVABILITY_THIN_SHIM = True
CANON_RUNTIME_OBSERVABILITY_EXPLICIT_EXPORTS_ONLY = True
CANON_RUNTIME_OBSERVABILITY_SHIM_OWNER = "runtime.runtime_observability"
__all__ = [
    "CANON_RUNTIME_OBSERVABILITY_AUDIT_ONLY",
    "CANON_RUNTIME_OBSERVABILITY_EXPLICIT_EXPORTS_ONLY",
    "CANON_RUNTIME_OBSERVABILITY_NO_DECISION_LOGIC",
    "CANON_RUNTIME_OBSERVABILITY_ONE_TRACE_STORY",
    "CANON_RUNTIME_OBSERVABILITY_OWNER",
    "CANON_RUNTIME_OBSERVABILITY_SHIM_OWNER",
    "CANON_RUNTIME_OBSERVABILITY_THIN_SHIM",
    "RuntimeObservability",
]

