from __future__ import annotations

from typing import Protocol, Sequence, runtime_checkable

from crm.crm_capability_contract import CrmCapabilityDescriptor
from crm.crm_connection_contract import CrmConnectionRef
from crm.crm_contact_contract import CrmContact
from crm.crm_deal_contract import CrmDeal
from crm.crm_note_contract import CrmNote
from crm.crm_pipeline_contract import CrmPipeline
from crm.crm_provider_contract import CrmProvider
from crm.crm_verification_contract import CrmVerificationRequest, CrmVerificationResult


@runtime_checkable
class CrmConnector(Protocol):
    provider: CrmProvider

    def capabilities(self) -> CrmCapabilityDescriptor: ...
    def verify_connection(self, connection: CrmConnectionRef) -> dict[str, object]: ...
    def list_pipelines(self, connection: CrmConnectionRef) -> Sequence[CrmPipeline]: ...
    def upsert_pipeline(self, connection: CrmConnectionRef, pipeline: CrmPipeline, *, idempotency_key: str) -> dict[str, object]: ...
    def upsert_contact(self, connection: CrmConnectionRef, contact: CrmContact, *, idempotency_key: str) -> dict[str, object]: ...
    def upsert_deal(self, connection: CrmConnectionRef, deal: CrmDeal, *, idempotency_key: str) -> dict[str, object]: ...
    def append_note(self, connection: CrmConnectionRef, note: CrmNote, *, idempotency_key: str) -> dict[str, object]: ...
    def verify_write(self, connection: CrmConnectionRef, request: CrmVerificationRequest) -> CrmVerificationResult: ...
    def build_snapshot(self, connection: CrmConnectionRef) -> dict[str, object]: ...
