from __future__ import annotations

POSTGRES_PROOF_CONNECT_TIMEOUT_SECONDS = 10
POSTGRES_PROOF_STATEMENT_TIMEOUT_MS = 60_000
POSTGRES_PROOF_LOCK_TIMEOUT_MS = 10_000

__all__ = [
    "POSTGRES_PROOF_CONNECT_TIMEOUT_SECONDS",
    "POSTGRES_PROOF_STATEMENT_TIMEOUT_MS",
    "POSTGRES_PROOF_LOCK_TIMEOUT_MS",
]
