ARTIFACT_CREATED = "artifact.created"
ARTIFACT_ARCHIVED = "artifact.archived"
ARTIFACT_FACT_TYPES = frozenset({ARTIFACT_CREATED, ARTIFACT_ARCHIVED})

__all__ = ["ARTIFACT_ARCHIVED", "ARTIFACT_CREATED", "ARTIFACT_FACT_TYPES"]
