from __future__ import annotations

from application.business_autonomy.channel_contracts import ChannelKind
from application.business_autonomy.provider_admin_contract import ProviderDefinition, ProviderSecretField

CANON_PROVIDER_CATALOG = True


def _token(label: str, secret_name: str, *, placeholder: str = "", kind: str = "token", required: bool = True) -> ProviderSecretField:
    return ProviderSecretField(field_key=secret_name, secret_name=secret_name, label=label, placeholder=placeholder, secret_kind=kind, required=required)


PROVIDERS: tuple[ProviderDefinition, ...] = (
    ProviderDefinition(
        provider_key="telegram_bot",
        title="Telegram Bot",
        connector_id="telegram",
        adapter_key="chatbot.telegram",
        channel_kind=ChannelKind.CHATBOT,
        domain="communications",
        description="Подключение бота Telegram как управляемого business channel.",
        secret_fields=(_token("Bot Token", "bot_token", placeholder="123456:ABC..."),),
        default_non_ai_mode="delegated",
        default_action_type="communications_write",
        messaging_channel="telegram",
        messaging_capabilities={"plain_text": True, "buttons": True, "attachments": True},
        messaging_live_probe_supported=True,
    ),
    ProviderDefinition(
        provider_key="whatsapp_cloud",
        title="WhatsApp Cloud",
        connector_id="whatsapp",
        adapter_key="chatbot.whatsapp",
        channel_kind=ChannelKind.CHATBOT,
        domain="communications",
        description="Подключение WhatsApp business messaging.",
        secret_fields=(
            _token("Access Token", "access_token", placeholder="EAAB..."),
            _token("Phone Number ID", "phone_number_id", placeholder="1234567890", kind="config"),
        ),
        default_non_ai_mode="delegated",
        default_action_type="communications_write",
        messaging_channel="whatsapp",
        messaging_capabilities={"plain_text": True, "buttons": True, "attachments": True},
        messaging_live_probe_supported=True,
    ),
    ProviderDefinition(
        provider_key="email_connector",
        title="Email Connector",
        connector_id="communications.email",
        adapter_key="chatbot.email",
        channel_kind=ChannelKind.CHATBOT,
        domain="communications",
        description="Email delivery and inbox connector for business communications.",
        secret_fields=(
            _token("SMTP/API Token", "api_token", placeholder="smtp-or-api-token"),
            _token("From Address", "from_address", placeholder="ops@example.com", kind="config"),
        ),
        default_non_ai_mode="delegated",
        default_action_type="communications_write",
        messaging_channel="email",
        messaging_capabilities={"plain_text": True, "html": True, "attachments": True, "subject_line": True},
        messaging_live_probe_supported=False,
    ),
    ProviderDefinition(
        provider_key="sms_connector",
        title="SMS Connector",
        connector_id="communications.sms",
        adapter_key="chatbot.sms",
        channel_kind=ChannelKind.CHATBOT,
        domain="communications",
        description="SMS gateway connector for transactional and campaign messaging.",
        secret_fields=(
            _token("API Token", "api_token", placeholder="sms-token"),
            _token("Sender ID", "sender_id", placeholder="BUSAIOS", kind="config"),
        ),
        default_non_ai_mode="delegated",
        default_action_type="communications_write",
        messaging_channel="sms",
        messaging_capabilities={"plain_text": True},
        messaging_live_probe_supported=False,
    ),
    ProviderDefinition(
        provider_key="call_tracking",
        title="Call Tracking",
        connector_id="communications.call_tracking",
        adapter_key="backoffice.call_tracking",
        channel_kind=ChannelKind.BACKOFFICE,
        domain="communications",
        description="Call tracking and attribution connector.",
        secret_fields=(
            _token("API Token", "api_token", placeholder="call-tracking-token"),
            _token("Workspace ID", "workspace_id", placeholder="workspace-1", kind="config"),
        ),
        default_non_ai_mode="delegated",
        default_action_type="task_create",
    ),
    ProviderDefinition(
        provider_key="generic_website",
        title="Generic Website",
        connector_id="website.site",
        adapter_key="website.default",
        channel_kind=ChannelKind.WEBSITE,
        domain="website",
        description="Подключение сайта как web-business system с supervised/low-autonomy path.",
        secret_fields=(
            _token("Webhook Secret", "webhook_secret", placeholder="site-webhook-secret", kind="signing_secret"),
            _token("Admin API Key", "admin_api_key", placeholder="optional-admin-key", kind="api_key"),
        ),
        default_non_ai_mode="supervised",
        default_action_type="profile_publish",
        messaging_channel="web_chat",
        messaging_capabilities={"plain_text": True, "buttons": True},
        messaging_live_probe_supported=False,
    ),
    ProviderDefinition(
        provider_key="webflow",
        title="Webflow",
        connector_id="website.webflow",
        adapter_key="website.webflow",
        channel_kind=ChannelKind.WEBSITE,
        domain="website",
        description="Webflow site/business connector.",
        secret_fields=(_token("Webflow Token", "api_token", placeholder="webflow-token", kind="api_key"),),
        default_non_ai_mode="supervised",
        default_action_type="profile_publish",
    ),
    ProviderDefinition(
        provider_key="wordpress",
        title="WordPress",
        connector_id="website.wordpress",
        adapter_key="website.wordpress",
        channel_kind=ChannelKind.WEBSITE,
        domain="website",
        description="WordPress site/business connector.",
        secret_fields=(
            _token("Application Password", "application_password", placeholder="xxxx xxxx xxxx", kind="password"),
            _token("Webhook Secret", "webhook_secret", placeholder="optional-webhook-secret", kind="signing_secret"),
        ),
        default_non_ai_mode="supervised",
        default_action_type="profile_publish",
    ),
    ProviderDefinition(
        provider_key="shopify",
        title="Shopify",
        connector_id="commerce.shopify",
        adapter_key="commerce.shopify",
        channel_kind=ChannelKind.COMMERCE,
        domain="commerce",
        description="Shopify commerce business connector.",
        secret_fields=(
            _token("Admin Access Token", "admin_access_token", placeholder="shpat_..."),
            _token("Webhook Secret", "webhook_secret", placeholder="shopify-webhook-secret", kind="signing_secret"),
        ),
        default_non_ai_mode="policy_guided",
        default_action_type="platform_listing_write",
    ),
    ProviderDefinition(
        provider_key="woocommerce",
        title="WooCommerce",
        connector_id="commerce.woocommerce",
        adapter_key="commerce.woocommerce",
        channel_kind=ChannelKind.COMMERCE,
        domain="commerce",
        description="WooCommerce store connector.",
        secret_fields=(
            _token("Consumer Key", "consumer_key", placeholder="ck_..."),
            _token("Consumer Secret", "consumer_secret", placeholder="cs_..."),
            _token("Store URL", "store_url", placeholder="https://shop.example.com", kind="url"),
        ),
        default_non_ai_mode="policy_guided",
        default_action_type="platform_listing_write",
    ),
    ProviderDefinition(
        provider_key="amazon_marketplace",
        title="Amazon Marketplace",
        connector_id="marketplace.amazon",
        adapter_key="commerce.amazon_marketplace",
        channel_kind=ChannelKind.COMMERCE,
        domain="marketplace",
        description="Amazon marketplace onboarding for product and order surfaces.",
        secret_fields=(
            _token("Refresh Token", "refresh_token", placeholder="amzn-refresh-token"),
            _token("Seller ID", "seller_id", placeholder="A1SELLER", kind="config"),
        ),
        default_non_ai_mode="policy_guided",
        default_action_type="platform_listing_write",
    ),
    ProviderDefinition(
        provider_key="ebay_marketplace",
        title="eBay Marketplace",
        connector_id="marketplace.ebay",
        adapter_key="commerce.ebay_marketplace",
        channel_kind=ChannelKind.COMMERCE,
        domain="marketplace",
        description="eBay marketplace onboarding for listings and order sync.",
        secret_fields=(
            _token("OAuth Token", "oauth_token", placeholder="ebay-token"),
            _token("Marketplace ID", "marketplace_id", placeholder="EBAY_US", kind="config"),
        ),
        default_non_ai_mode="policy_guided",
        default_action_type="platform_listing_write",
    ),
    ProviderDefinition(
        provider_key="etsy_marketplace",
        title="Etsy Marketplace",
        connector_id="marketplace.etsy",
        adapter_key="commerce.etsy_marketplace",
        channel_kind=ChannelKind.COMMERCE,
        domain="marketplace",
        description="Etsy marketplace onboarding for shop catalog and order sync.",
        secret_fields=(
            _token("API Key", "api_key", placeholder="etsy-api-key"),
            _token("Shop ID", "shop_id", placeholder="123456", kind="config"),
        ),
        default_non_ai_mode="policy_guided",
        default_action_type="platform_listing_write",
    ),
    ProviderDefinition(
        provider_key="wildberries_marketplace",
        title="Wildberries Marketplace",
        connector_id="marketplace.wildberries",
        adapter_key="commerce.wildberries_marketplace",
        channel_kind=ChannelKind.COMMERCE,
        domain="marketplace",
        description="Wildberries marketplace connector.",
        secret_fields=(
            _token("API Token", "api_token", placeholder="wb-token"),
        ),
        default_non_ai_mode="policy_guided",
        default_action_type="platform_listing_write",
    ),
    ProviderDefinition(
        provider_key="ozon_marketplace",
        title="Ozon Marketplace",
        connector_id="marketplace.ozon",
        adapter_key="commerce.ozon_marketplace",
        channel_kind=ChannelKind.COMMERCE,
        domain="marketplace",
        description="Ozon marketplace connector.",
        secret_fields=(
            _token("Client ID", "client_id", placeholder="ozon-client-id", kind="config"),
            _token("API Key", "api_key", placeholder="ozon-api-key"),
        ),
        default_non_ai_mode="policy_guided",
        default_action_type="platform_listing_write",
    ),
    ProviderDefinition(
        provider_key="hubspot",
        title="HubSpot",
        connector_id="crm.hubspot",
        adapter_key="backoffice.hubspot",
        channel_kind=ChannelKind.BACKOFFICE,
        domain="crm",
        description="HubSpot CRM connector.",
        secret_fields=(_token("Private App Token", "private_app_token", placeholder="pat-..."),),
        default_non_ai_mode="delegated",
        default_action_type="task_create",
    ),
    ProviderDefinition(
        provider_key="meta_ads",
        title="Meta Ads",
        connector_id="ads.meta",
        adapter_key="campaign_ads.meta",
        channel_kind=ChannelKind.CAMPAIGN_ADS,
        domain="ads",
        description="Meta Ads campaign connector.",
        secret_fields=(
            _token("Access Token", "access_token", placeholder="EAAB..."),
            _token("Ad Account ID", "account_id", placeholder="act_123456", kind="config"),
        ),
        default_non_ai_mode="supervised",
        default_action_type="campaign_launch",
    ),

    ProviderDefinition(
        provider_key="tiktok_ads",
        title="TikTok Ads",
        connector_id="ads.tiktok",
        adapter_key="campaign_ads.tiktok",
        channel_kind=ChannelKind.CAMPAIGN_ADS,
        domain="ads",
        description="TikTok Ads campaign connector.",
        secret_fields=(
            _token("Access Token", "access_token", placeholder="tiktok-access-token"),
            _token("Advertiser ID", "advertiser_id", placeholder="advertiser-id", kind="config"),
        ),
        default_non_ai_mode="supervised",
        default_action_type="campaign_launch",
    ),
    ProviderDefinition(
        provider_key="postgres_runtime",
        title="Postgres Runtime",
        connector_id="platform.postgres",
        adapter_key="api.default",
        channel_kind=ChannelKind.API_BUSINESS,
        domain="platform_infra",
        description="Production Postgres backend for platform state and read/write surfaces.",
        secret_fields=(
            _token("Postgres DSN", "dsn", placeholder="postgres://user:pass@host:5432/db", kind="dsn"),
        ),
        supports_business_onboarding=False,
        default_non_ai_mode="delegated",
        default_action_type="internal_execution",
    ),
    ProviderDefinition(
        provider_key="redis_runtime",
        title="Redis Runtime",
        connector_id="platform.redis",
        adapter_key="api.default",
        channel_kind=ChannelKind.API_BUSINESS,
        domain="platform_infra",
        description="Production Redis backend for idempotency, leases and fast coordination.",
        secret_fields=(
            _token("Redis URL", "redis_url", placeholder="redis://default:password@host:6379", kind="dsn"),
            _token("Redis Token", "redis_token", placeholder="optional-token", kind="api_key", required=False),
        ),
        supports_business_onboarding=False,
        default_non_ai_mode="delegated",
        default_action_type="internal_execution",
    ),
    ProviderDefinition(
        provider_key="clickhouse_export",
        title="ClickHouse Export",
        connector_id="platform.clickhouse",
        adapter_key="api.default",
        channel_kind=ChannelKind.API_BUSINESS,
        domain="platform_infra",
        description="ClickHouse exporter for fleet reporting and analytics pipelines.",
        secret_fields=(
            _token("Endpoint", "endpoint", placeholder="https://clickhouse.example.com", kind="url"),
            _token("Database", "database", placeholder="analytics", kind="config"),
            _token("Username", "username", placeholder="default", kind="username", required=False),
            _token("Password", "password", placeholder="secret", kind="password", required=False),
        ),
        supports_business_onboarding=False,
        default_non_ai_mode="delegated",
        default_action_type="internal_execution",
    ),
    ProviderDefinition(
        provider_key="google_ads",
        title="Google Ads",
        connector_id="ads.google",
        adapter_key="campaign_ads.google",
        channel_kind=ChannelKind.CAMPAIGN_ADS,
        domain="ads",
        description="Google Ads campaign connector.",
        secret_fields=(
            _token("Developer Token", "developer_token", placeholder="google-dev-token"),
            _token("Refresh Token", "refresh_token", placeholder="1//..."),
            _token("Client ID", "client_id", placeholder="client-id.apps.googleusercontent.com", kind="oauth_client"),
            _token("Client Secret", "client_secret", placeholder="client-secret", kind="oauth_client_secret"),
        ),
        default_non_ai_mode="supervised",
        default_action_type="campaign_launch",
    ),
)


def provider_map() -> dict[str, ProviderDefinition]:
    return {item.provider_key: item for item in PROVIDERS}


__all__ = ["CANON_PROVIDER_CATALOG", "PROVIDERS", "provider_map"]
