from execution.effectors.market_intelligence.sync_marketplace_catalog import SyncMarketplaceCatalogEffector
from execution.effectors.market_intelligence.sync_ads_library import SyncAdsLibraryEffector
from execution.effectors.market_intelligence.sync_competitor_analytics import SyncCompetitorAnalyticsEffector
from execution.effectors.market_intelligence.sync_search_intelligence import SyncSearchIntelligenceEffector
from execution.effectors.market_intelligence.sync_professional_discussions import SyncProfessionalDiscussionsEffector
from execution.effectors.market_intelligence.sync_content_publications import SyncContentPublicationsEffector
from execution.effectors.market_intelligence.sync_app_store_intelligence import SyncAppStoreIntelligenceEffector
from execution.effectors.market_intelligence.sync_review_intelligence import SyncReviewIntelligenceEffector
from execution.effectors.market_intelligence.crawl_competitor_landing import CrawlCompetitorLandingEffector
from execution.effectors.market_intelligence.sync_video_platform import SyncVideoPlatformEffector
from execution.effectors.market_intelligence.sync_ads_spy_intelligence import SyncAdsSpyIntelligenceEffector
from execution.effectors.market_intelligence.sync_newsletter_intelligence import SyncNewsletterIntelligenceEffector

__all__ = [name for name in globals() if name.endswith('Effector')]
