from __future__ import annotations

import os
from pathlib import Path

"""Fail-closed dependency lock contract.

The default check preserves the historical top-level drift guard:
`requirements.txt` and `requirements.lock.txt` must contain the same direct pins.

Release/pre-release gates require separate transitive lock evidence. This avoids
mixing two different contracts in one file:

- `requirements.lock.txt` is the direct dependency policy mirror.
- `requirements.release.lock.txt` is a requirements-style transitive lock, or
  `uv.lock` / `poetry.lock` is the resolver-native transitive lock.

This keeps dev installs lightweight while preventing production release claims
from passing on top-level-only dependency evidence.
"""


ROOT = Path(__file__).resolve().parents[2]
REQUIREMENTS = ROOT / "requirements.txt"
TOP_LEVEL_LOCK = ROOT / "requirements.lock.txt"
RELEASE_REQUIREMENTS_LOCK = ROOT / "requirements.release.lock.txt"
UV_LOCK = ROOT / "uv.lock"
POETRY_LOCK = ROOT / "poetry.lock"
DOCKERFILE = ROOT / "Dockerfile"

_RELEASE_LOCK_MARKERS = (
    "BAIOS_TRANSITIVE_LOCK: true",
    "Generated by pip-compile",
    "This file was autogenerated by uv",
    "# This file is automatically @generated by Poetry",
)

_TOP_LEVEL_ONLY_MARKERS = (
    "Locked top-level dependencies",
    "Transitive dependency locking can be added later",
    "top-level dependency set",
)


def _strip_inline_comment(line: str) -> str:
    if " #" in line:
        return line.split(" #", 1)[0].strip()
    return line.strip()


def _normalized_requirement_lines(path: Path) -> set[str]:
    if not path.exists():
        raise FileNotFoundError(path)
    items: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = _strip_inline_comment(raw.strip())
        if not line or line.startswith("#"):
            continue
        if line.startswith(("--", "-r ", "-c ")):
            continue
        items.add(line)
    return items


def _package_key(requirement: str) -> str:
    head = requirement.strip().split(";", 1)[0].strip()
    for marker in ("===", "==", ">=", "<=", "~=", "!=", ">", "<"):
        if marker in head:
            head = head.split(marker, 1)[0].strip()
            break
    if "[" in head:
        head = head.split("[", 1)[0].strip()
    return head.replace("_", "-").lower()


def _release_lock_required() -> bool:
    return str(os.getenv("BAIOS_REQUIRE_TRANSITIVE_DEPENDENCY_LOCK") or "").strip().lower() in {
        "1",
        "true",
        "yes",
        "release",
        "required",
    }


def _container_install_requires_release_lock() -> bool:
    """Require release-lock validation whenever the container install path uses it.

    This keeps the Docker workflow fail-closed even if the workflow invokes the
    generic lock checker without an explicit release env flag. The dependency
    contract follows the production install path, not a duplicated workflow brain.
    """

    if not DOCKERFILE.exists():
        return False
    text = DOCKERFILE.read_text(encoding="utf-8")
    return "requirements.release.lock.txt" in text or "pip install --require-hashes" in text


def _path_has_any_marker(path: Path, markers: tuple[str, ...]) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    return any(marker in text for marker in markers)


def _check_top_level_lock() -> tuple[bool, str]:
    requirements = _normalized_requirement_lines(REQUIREMENTS)
    locked = _normalized_requirement_lines(TOP_LEVEL_LOCK)
    missing_from_lock = sorted(requirements - locked)
    extra_in_lock = sorted(locked - requirements)
    if missing_from_lock or extra_in_lock:
        lines = ["requirements top-level lock drift detected"]
        if missing_from_lock:
            lines.append("missing_from_lock:")
            lines.extend(f"  - {item}" for item in missing_from_lock)
        if extra_in_lock:
            lines.append("extra_in_lock:")
            lines.extend(f"  - {item}" for item in extra_in_lock)
        return False, "\n".join(lines)
    return True, f"requirements top-level lock is in sync ({len(locked)} direct dependencies)"


def _check_requirements_release_lock() -> tuple[bool, str] | None:
    if not RELEASE_REQUIREMENTS_LOCK.exists():
        return None
    requirements = _normalized_requirement_lines(REQUIREMENTS)
    release_locked = _normalized_requirement_lines(RELEASE_REQUIREMENTS_LOCK)
    requirement_keys = {_package_key(item) for item in requirements}
    release_keys = {_package_key(item) for item in release_locked}
    missing = sorted(requirement_keys - release_keys)
    if missing:
        return False, "requirements.release.lock.txt misses direct dependency keys: " + ", ".join(missing)
    has_marker = _path_has_any_marker(RELEASE_REQUIREMENTS_LOCK, _RELEASE_LOCK_MARKERS)
    has_transitive_depth = len(release_locked) > len(requirements)
    has_top_level_marker = _path_has_any_marker(RELEASE_REQUIREMENTS_LOCK, _TOP_LEVEL_ONLY_MARKERS)
    if has_top_level_marker:
        return False, "requirements.release.lock.txt is marked as top-level-only"
    if not has_marker and not has_transitive_depth:
        return False, "requirements.release.lock.txt does not prove transitive dependency locking"
    return True, f"requirements release lock present ({len(release_locked)} pinned entries)"


def _check_native_release_lock() -> tuple[bool, str] | None:
    if UV_LOCK.exists():
        text = UV_LOCK.read_text(encoding="utf-8")
        if "[[package]]" not in text and "version" not in text:
            return False, "uv.lock exists but does not look like a package lock"
        return True, "uv.lock transitive lock present"
    if POETRY_LOCK.exists():
        text = POETRY_LOCK.read_text(encoding="utf-8")
        if "[[package]]" not in text:
            return False, "poetry.lock exists but does not look like a package lock"
        return True, "poetry.lock transitive lock present"
    return None


def _check_release_lock() -> tuple[bool, str]:
    requirements_style = _check_requirements_release_lock()
    if requirements_style is not None:
        return requirements_style
    native = _check_native_release_lock()
    if native is not None:
        return native
    return (
        False,
        "release requires a transitive lock: add requirements.release.lock.txt, uv.lock, or poetry.lock",
    )


def main() -> int:
    ok, message = _check_top_level_lock()
    if not ok:
        print(message)
        return 1
    if _release_lock_required() or _container_install_requires_release_lock():
        release_ok, release_message = _check_release_lock()
        if not release_ok:
            print(message)
            print(release_message)
            return 1
        print(f"{message}; {release_message}")
        return 0
    print(message)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
