BUSINESS_SERVICE_CREATED = "business_service.created"
BUSINESS_SERVICE_UPDATED = "business_service.updated"
BUSINESS_SERVICE_ARCHIVED = "business_service.archived"
BUSINESS_SERVICE_FACT_TYPES = frozenset({BUSINESS_SERVICE_CREATED, BUSINESS_SERVICE_UPDATED, BUSINESS_SERVICE_ARCHIVED})

__all__ = ["BUSINESS_SERVICE_ARCHIVED", "BUSINESS_SERVICE_CREATED", "BUSINESS_SERVICE_FACT_TYPES", "BUSINESS_SERVICE_UPDATED"]
