DOCUMENT_CREATED = "document.created"
DOCUMENT_REVISED = "document.revised"
DOCUMENT_ARCHIVED = "document.archived"
DOCUMENT_FACT_TYPES = frozenset({DOCUMENT_CREATED, DOCUMENT_REVISED, DOCUMENT_ARCHIVED})

__all__ = ["DOCUMENT_ARCHIVED", "DOCUMENT_CREATED", "DOCUMENT_FACT_TYPES", "DOCUMENT_REVISED"]
