TASK_CREATED = "task.created"
TASK_STARTED = "task.started"
TASK_COMPLETED = "task.completed"
TASK_FAILED = "task.failed"
TASK_CANCELLED = "task.cancelled"
TASK_FACT_TYPES = frozenset({TASK_CREATED, TASK_STARTED, TASK_COMPLETED, TASK_FAILED, TASK_CANCELLED})

__all__ = ["TASK_CANCELLED", "TASK_COMPLETED", "TASK_CREATED", "TASK_FACT_TYPES", "TASK_FAILED", "TASK_STARTED"]
