from __future__ import annotations

"""Explicit compatibility wrapper with a real module file."""

CANON_COMPAT_SHIM = True

from config import INTENT_CONFIDENCE_FLOOR as INTENT_CONFIDENCE_FLOOR
from config import HIGH_VALUE_REVENUE_THRESHOLD as HIGH_VALUE_REVENUE_THRESHOLD
from config import DEDUP_WINDOW_MINUTES as DEDUP_WINDOW_MINUTES
from config import MATCH_BLOCK_RISK_THRESHOLD as MATCH_BLOCK_RISK_THRESHOLD
from config import HIGH_RISK_BUSINESS_THRESHOLD as HIGH_RISK_BUSINESS_THRESHOLD
from config import NO_RESPONSE_RATE_LIMIT as NO_RESPONSE_RATE_LIMIT
from config import REPUTATION_FLOOR as REPUTATION_FLOOR
from config import MAX_LOAD_RATIO as MAX_LOAD_RATIO
from config import MONOPOLY_LIMIT as MONOPOLY_LIMIT
from config import BAD_OUTCOME_ROLLBACK_THRESHOLD as BAD_OUTCOME_ROLLBACK_THRESHOLD

__all__ = ['INTENT_CONFIDENCE_FLOOR', 'HIGH_VALUE_REVENUE_THRESHOLD', 'DEDUP_WINDOW_MINUTES', 'MATCH_BLOCK_RISK_THRESHOLD', 'HIGH_RISK_BUSINESS_THRESHOLD', 'NO_RESPONSE_RATE_LIMIT', 'REPUTATION_FLOOR', 'MAX_LOAD_RATIO', 'MONOPOLY_LIMIT', 'BAD_OUTCOME_ROLLBACK_THRESHOLD']
