from __future__ import annotations

"""Explicit compatibility wrapper with a real module file."""

CANON_COMPAT_SHIM = True

from config import CAUSAL_RECENCY_WEIGHT as CAUSAL_RECENCY_WEIGHT
from config import MIN_REPLAY_SAMPLE_SIZE as MIN_REPLAY_SAMPLE_SIZE
from config import POLICY_CHANGE_EPSILON as POLICY_CHANGE_EPSILON
from config import POLICY_MAX_ABSOLUTE_ADJUSTMENT as POLICY_MAX_ABSOLUTE_ADJUSTMENT
from config import POLICY_MIN_OUTCOME_ROWS_FOR_UPDATE as POLICY_MIN_OUTCOME_ROWS_FOR_UPDATE
from config import POLICY_MIN_PER_BUSINESS_ROWS as POLICY_MIN_PER_BUSINESS_ROWS
from config import POLICY_PROMOTION_MIN_CONVERSION_RATE as POLICY_PROMOTION_MIN_CONVERSION_RATE
from config import POLICY_ROLLBACK_MAX_CONVERSION_RATE as POLICY_ROLLBACK_MAX_CONVERSION_RATE
from config import POLICY_ROLLBACK_MIN_BAD_OUTCOME_RATE as POLICY_ROLLBACK_MIN_BAD_OUTCOME_RATE

__all__ = ['MIN_REPLAY_SAMPLE_SIZE', 'POLICY_PROMOTION_MIN_CONVERSION_RATE', 'POLICY_ROLLBACK_MAX_CONVERSION_RATE', 'POLICY_ROLLBACK_MIN_BAD_OUTCOME_RATE', 'POLICY_MAX_ABSOLUTE_ADJUSTMENT', 'POLICY_MIN_OUTCOME_ROWS_FOR_UPDATE', 'POLICY_MIN_PER_BUSINESS_ROWS', 'POLICY_CHANGE_EPSILON', 'CAUSAL_RECENCY_WEIGHT']
