from __future__ import annotations

CANON_COMPAT_SHIM = True

from decimal import Decimal

from core.finance.strategic.types import Scenario
from core.strategic_horizon.engine import StrategicMode

DEFAULT_STRATEGIC_FINANCE_SCENARIOS: tuple[Scenario, ...] = (
    Scenario(
        name=StrategicMode.DEFENSE.value,
        revenue_multiplier=Decimal("0.96"),
        cost_multiplier=Decimal("0.90"),
        probability=Decimal("0.16"),
        cash_pressure=Decimal("0.10"),
        margin_deterioration=Decimal("0.02"),
        channel_decay=Decimal("0.03"),
        working_capital_pressure=Decimal("0.04"),
        downside_risk=Decimal("0.18"),
        capital_efficiency_bias=Decimal("0.90"),
        notes=("capital preservation mode", "protect runway floor"),
        channel_bias={"marketing": Decimal("0.85"), "sales": Decimal("0.90"), "operations": Decimal("1.05")},
        segment_bias={"existing": Decimal("1.05"), "new": Decimal("0.82")},
        product_bias={"core": Decimal("1.08"), "experiments": Decimal("0.76")},
        entity_bias={"group": Decimal("1.02"), "intl": Decimal("0.88")},
        entity_scope=("group",),
        downside_tree=("revenue_softness", "budget_freeze", "approval_delay"),
        downside_tree_weights={"revenue_softness": Decimal("0.05"), "budget_freeze": Decimal("0.04"), "approval_delay": Decimal("0.03")},
        working_capital_dynamics={"receivable_days_stretch": Decimal("0.0020"), "inventory_days_build": Decimal("0.0010"), "payable_days_support": Decimal("0.0008")},
    ),
    Scenario(
        name="balanced",
        revenue_multiplier=Decimal("1.02"),
        cost_multiplier=Decimal("0.99"),
        probability=Decimal("0.24"),
        cash_pressure=Decimal("0.08"),
        margin_deterioration=Decimal("0.02"),
        channel_decay=Decimal("0.03"),
        working_capital_pressure=Decimal("0.04"),
        downside_risk=Decimal("0.12"),
        capital_efficiency_bias=Decimal("0.78"),
        notes=("balanced growth",),
        channel_bias={"marketing": Decimal("1.00"), "sales": Decimal("1.00"), "operations": Decimal("1.00")},
        segment_bias={"existing": Decimal("1.00"), "new": Decimal("1.00")},
        product_bias={"core": Decimal("1.02"), "expansion": Decimal("0.98")},
        entity_bias={"group": Decimal("1.00"), "intl": Decimal("0.99")},
        entity_scope=("group", "product"),
        downside_tree=("moderate_variance",),
        downside_tree_weights={"moderate_variance": Decimal("0.03")},
        working_capital_dynamics={"receivable_days_stretch": Decimal("0.0010"), "inventory_days_build": Decimal("0.0008"), "payable_days_support": Decimal("0.0007")},
    ),
    Scenario(
        name="growth",
        revenue_multiplier=Decimal("1.14"),
        cost_multiplier=Decimal("1.05"),
        probability=Decimal("0.18"),
        cash_pressure=Decimal("0.22"),
        margin_deterioration=Decimal("0.05"),
        channel_decay=Decimal("0.04"),
        working_capital_pressure=Decimal("0.08"),
        downside_risk=Decimal("0.24"),
        capital_efficiency_bias=Decimal("0.60"),
        notes=("growth biased",),
        channel_bias={"marketing": Decimal("1.10"), "sales": Decimal("1.05"), "operations": Decimal("0.92")},
        segment_bias={"existing": Decimal("0.96"), "new": Decimal("1.08")},
        product_bias={"core": Decimal("0.98"), "new_products": Decimal("1.12")},
        entity_bias={"group": Decimal("0.99"), "intl": Decimal("1.08")},
        entity_scope=("group", "product", "channel"),
        downside_tree=("cac_inflation", "approval_delay", "channel_decay_spike"),
        downside_tree_weights={"cac_inflation": Decimal("0.06"), "approval_delay": Decimal("0.03"), "channel_decay_spike": Decimal("0.04")},
        working_capital_dynamics={"receivable_days_stretch": Decimal("0.0024"), "inventory_days_build": Decimal("0.0014"), "payable_days_support": Decimal("0.0005")},
    ),
    Scenario(
        name="efficiency",
        revenue_multiplier=Decimal("1.01"),
        cost_multiplier=Decimal("0.94"),
        probability=Decimal("0.14"),
        cash_pressure=Decimal("0.06"),
        margin_deterioration=Decimal("0.01"),
        channel_decay=Decimal("0.02"),
        working_capital_pressure=Decimal("0.03"),
        downside_risk=Decimal("0.10"),
        capital_efficiency_bias=Decimal("0.95"),
        notes=("margin first",),
        channel_bias={"marketing": Decimal("0.92"), "sales": Decimal("0.98"), "operations": Decimal("1.08")},
        segment_bias={"existing": Decimal("1.04"), "new": Decimal("0.90")},
        product_bias={"core": Decimal("1.06"), "new_products": Decimal("0.82")},
        entity_bias={"group": Decimal("1.03"), "intl": Decimal("0.94")},
        entity_scope=("group", "channel"),
        downside_tree=("margin_protection",),
        downside_tree_weights={"margin_protection": Decimal("0.02")},
        working_capital_dynamics={"receivable_days_stretch": Decimal("0.0008"), "inventory_days_build": Decimal("0.0004"), "payable_days_support": Decimal("0.0012")},
    ),
    Scenario(
        name="recovery",
        revenue_multiplier=Decimal("1.06"),
        cost_multiplier=Decimal("1.00"),
        probability=Decimal("0.12"),
        cash_pressure=Decimal("0.12"),
        margin_deterioration=Decimal("0.03"),
        channel_decay=Decimal("0.05"),
        working_capital_pressure=Decimal("0.05"),
        downside_risk=Decimal("0.16"),
        capital_efficiency_bias=Decimal("0.72"),
        notes=("recover from soft dip",),
        channel_bias={"marketing": Decimal("1.02"), "sales": Decimal("1.03"), "operations": Decimal("0.97")},
        segment_bias={"existing": Decimal("1.03"), "new": Decimal("0.98")},
        product_bias={"core": Decimal("1.04"), "retention_products": Decimal("1.06")},
        entity_bias={"group": Decimal("1.01"), "intl": Decimal("1.00")},
        entity_scope=("group", "product"),
        downside_tree=("gradual_recovery", "cash_discipline"),
        downside_tree_weights={"gradual_recovery": Decimal("0.03"), "cash_discipline": Decimal("0.02")},
        working_capital_dynamics={"receivable_days_stretch": Decimal("0.0012"), "inventory_days_build": Decimal("0.0007"), "payable_days_support": Decimal("0.0008")},
    ),
    Scenario(
        name="liquidity_stress",
        revenue_multiplier=Decimal("0.88"),
        cost_multiplier=Decimal("1.02"),
        probability=Decimal("0.10"),
        cash_pressure=Decimal("0.32"),
        margin_deterioration=Decimal("0.07"),
        channel_decay=Decimal("0.07"),
        working_capital_pressure=Decimal("0.11"),
        downside_risk=Decimal("0.30"),
        capital_efficiency_bias=Decimal("0.98"),
        notes=("liquidity stress", "slow approvals"),
        channel_bias={"marketing": Decimal("0.78"), "sales": Decimal("0.84"), "operations": Decimal("1.12")},
        segment_bias={"existing": Decimal("1.08"), "new": Decimal("0.72")},
        product_bias={"core": Decimal("1.05"), "new_products": Decimal("0.68")},
        entity_bias={"group": Decimal("1.01"), "intl": Decimal("0.80"), "treasury": Decimal("1.12")},
        entity_scope=("group", "treasury"),
        downside_tree=("working_capital_squeeze", "delayed_collection", "supplier_prepayment"),
        downside_tree_weights={"working_capital_squeeze": Decimal("0.07"), "delayed_collection": Decimal("0.06"), "supplier_prepayment": Decimal("0.05")},
        working_capital_dynamics={"receivable_days_stretch": Decimal("0.0031"), "inventory_days_build": Decimal("0.0020"), "payable_days_support": Decimal("0.0002")},
    ),
    Scenario(
        name="base",
        revenue_multiplier=Decimal("1.00"),
        cost_multiplier=Decimal("1.00"),
        probability=Decimal("0.06"),
        cash_pressure=Decimal("0.09"),
        margin_deterioration=Decimal("0.02"),
        channel_decay=Decimal("0.03"),
        working_capital_pressure=Decimal("0.04"),
        downside_risk=Decimal("0.11"),
        capital_efficiency_bias=Decimal("0.75"),
        notes=("neutral baseline",),
        channel_bias={"marketing": Decimal("1.00"), "sales": Decimal("1.00"), "operations": Decimal("1.00")},
        segment_bias={"existing": Decimal("1.00"), "new": Decimal("1.00")},
        product_bias={"core": Decimal("1.00")},
        entity_bias={"group": Decimal("1.00")},
        entity_scope=("group",),
        downside_tree=("baseline_variance",),
        downside_tree_weights={"baseline_variance": Decimal("0.02")},
        working_capital_dynamics={"receivable_days_stretch": Decimal("0.0010"), "inventory_days_build": Decimal("0.0008"), "payable_days_support": Decimal("0.0008")},
    ),
)
