from __future__ import annotations

OPERATOR_MESSAGE_OPEN = "message_open"
OPERATOR_CONTENT_ENGAGE = "content_engage"
OPERATOR_PRICE_VIEW = "price_view"
OPERATOR_PAYMENT_ATTEMPT = "payment_attempt"
OPERATOR_PAYMENT_SUCCESS = "payment_success"
OPERATOR_REFUND_SIGNAL = "refund_signal"
OPERATOR_QUESTION = "question_asked"
OPERATOR_RAGE = "rage_click"
OPERATOR_RETURN = "return_after_gap"
OPERATOR_SUPPORT_RELIEF = "support_relief"

ALL_OPERATOR_KEYS: tuple[str, ...] = (
    OPERATOR_MESSAGE_OPEN,
    OPERATOR_CONTENT_ENGAGE,
    OPERATOR_PRICE_VIEW,
    OPERATOR_PAYMENT_ATTEMPT,
    OPERATOR_PAYMENT_SUCCESS,
    OPERATOR_REFUND_SIGNAL,
    OPERATOR_QUESTION,
    OPERATOR_RAGE,
    OPERATOR_RETURN,
    OPERATOR_SUPPORT_RELIEF,
)
