from __future__ import annotations

CHANNEL_TELEGRAM = "telegram"
CHANNEL_WHATSAPP = "whatsapp"
CHANNEL_SMS = "sms"
CHANNEL_EMAIL = "email"
CHANNEL_MESSENGER = "messenger"
CHANNEL_INSTAGRAM = "instagram"
CHANNEL_WEB_CHAT = "web_chat"
CHANNEL_API = "api"
CHANNEL_LINE = "line"
CHANNEL_WECHAT = "wechat"
CHANNEL_KAKAOTALK = "kakaotalk"
CHANNEL_VIBER = "viber"
CHANNEL_SLACK = "slack"
CHANNEL_DISCORD = "discord"

ALL_CHANNELS = (
    CHANNEL_TELEGRAM,
    CHANNEL_WHATSAPP,
    CHANNEL_SMS,
    CHANNEL_EMAIL,
    CHANNEL_MESSENGER,
    CHANNEL_INSTAGRAM,
    CHANNEL_WEB_CHAT,
    CHANNEL_API,
    CHANNEL_LINE,
    CHANNEL_WECHAT,
    CHANNEL_KAKAOTALK,
    CHANNEL_VIBER,
    CHANNEL_SLACK,
    CHANNEL_DISCORD,
)

CHANNELS = list(ALL_CHANNELS)
