PARTNER_CREATED = "partner.created"
PARTNER_ARCHIVED = "partner.archived"
PARTNER_FACT_TYPES = frozenset({PARTNER_CREATED, PARTNER_ARCHIVED})

__all__ = ["PARTNER_ARCHIVED", "PARTNER_CREATED", "PARTNER_FACT_TYPES"]
