"""Traffic strategy service — 7d campaign plan generation.

TrafficStrategyService.plan_7d() produces a platform-agnostic TrafficPlan.

When creative_generator supports generate_async() (i.e. is an
LLMCreativeGenerator), interests from the LLM response are merged with
heuristic interests from AudienceSelector.

Otherwise (plain CreativeGenerator), audience falls back to heuristic-only.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from core.traffic.audience_selector import AudienceSelector
from core.traffic.bid_manager import BidManager
from core.traffic.budget_allocator import BudgetAllocator
from core.traffic.campaign_factory import CampaignFactory
from core.traffic.contracts import TrafficCreative, TrafficPlan
from core.traffic.creative_generator import CreativeGenerator


@dataclass(frozen=True)
class TrafficStrategyService:
    """Plan traffic actions for a 7d profit sprint.

    Produces a platform-agnostic TrafficPlan that AdsSpecBuilder
    translates into AdsService commands.

    creative_generator may be a plain CreativeGenerator (sync, no I/O)
    or an LLMCreativeGenerator (async, enriched copy + targeting interests).
    """

    campaign_factory: CampaignFactory
    audience_selector: AudienceSelector
    creative_generator: CreativeGenerator  # or LLMCreativeGenerator (duck-typed)
    budget_allocator: BudgetAllocator
    bid_manager: BidManager

    def plan_7d(
        self,
        *,
        tenant_id: str,
        platform: str,
        account_id: str,
        what: str,
        offer_title: str,
        region: str,
        total_budget_minor_7d: int,
        budget_currency: str,
        target_cac_minor: int,
        destination: dict,
        seed: str,
    ) -> TrafficPlan:
        daily = self.budget_allocator.daily_from_total(
            total_minor_7d=int(total_budget_minor_7d or 0)
        )

        # --- Heuristic interests (always available, sync) ---
        heuristic_interests = self.audience_selector.suggest_interests(what=what)

        # --- Creative + LLM interests ---
        creative: TrafficCreative
        llm_interests: list[str] = []

        gen = self.creative_generator
        build_with_interests = getattr(gen, "build_with_interests", None)
        if callable(build_with_interests):
            creative, llm_interests = build_with_interests(
                what=what,
                offer_title=offer_title,
                region=region,
                seed=seed,
            )
        else:
            creative = gen.build(what=what, offer_title=offer_title, seed=seed)

        # --- Merge interests ---
        if hasattr(self.audience_selector, "merge_llm_interests"):
            interests = self.audience_selector.merge_llm_interests(
                heuristic=heuristic_interests, llm=llm_interests
            )
        else:
            interests = heuristic_interests

        campaign = self.campaign_factory.build(
            name=f"BusinesAIOS Sprint 7d — {offer_title[:24]}",
            objective_kind="leads",
            target_cac_minor=int(target_cac_minor or 0),
            currency=str(budget_currency),
            daily_budget_minor=int(daily),
            budget_currency=str(budget_currency),
            audience_region=str(region),
            creative=creative,
            destination=destination,
            interests=interests,
        )
        return TrafficPlan(
            platform=str(platform),
            account_id=str(account_id),
            campaign=campaign,
            notes="autogenerated_by_businesaios",
            metadata={
                "tenant_id": str(tenant_id),
                "seed": str(seed),
                "bid_hint": self.bid_manager.initial_bid_hint(
                    target_cac_minor=int(target_cac_minor or 0)
                ),
                "creative_source": "llm" if llm_interests else "heuristic",
            },
        )

