PERSON_CREATED = "person.created"
PERSON_ARCHIVED = "person.archived"
PERSON_FACT_TYPES = frozenset({PERSON_CREATED, PERSON_ARCHIVED})

__all__ = ["PERSON_ARCHIVED", "PERSON_CREATED", "PERSON_FACT_TYPES"]
