from __future__ import annotations

from typing import Protocol

from .types import ApprovalDecision, OverrideRecord


class HumanGovernancePolicyContract(Protocol):
    def is_terminal(self, status: str) -> bool: ...

    def is_open_queue_status(self, status: str) -> bool: ...

    def needs_approval(self, status: str) -> bool: ...

    def ensure_actionable(self, status: str) -> None: ...

    def validate_actor_id(self, actor_id: str) -> str: ...

    def validate_reason(self, reason: str) -> str: ...

    def validate_approval_decision(self, decision: ApprovalDecision) -> ApprovalDecision: ...

    def validate_override_record(self, record: OverrideRecord) -> OverrideRecord: ...
